# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'facebookLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for facebookLogin

  pod 'Firebase/Auth'  
  pod 'FacebookSDK'
  pod 'Firebase/Core'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'SDWebImage/WebP'

end
